pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

- script: gem install bundler
  displayName: 'install bundler'

- script: cd android

- script: bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: bundle exec fastlane -v
  displayName: 'bundle exec fastlane -v'
