# config

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'

# preparation

- script: gem install bundler
  displayName: 'install bundler'

- script: |
    cd android
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    cd android
    bundle exec fastlane -v
  displayName: 'bundle exec fastlane -v'

# secure files

- task: DownloadSecureFile@1
  inputs:
    secureFile: google_play_key.json

- task: DownloadSecureFile@1
  inputs:
    secureFile: zaehlerstand.keystore

- script: |
    echo "##vso[task.setvariable variable=JSON_KEY_FILE]$env:DOWNLOADSECUREFILE1_SECUREFILEPATH"
    echo "##vso[task.setvariable variable=KEYSTORE_FILE]$env:DOWNLOADSECUREFILE2_SECUREFILEPATH"

# lanes

- script: |
    cd android
    bundle exec fastlane environment
  displayName: 'bundle exec fastlane environment'

- script: |
    cd android
    bundle exec fastlane all
  displayName: 'bundle exec fastlane all'
