jobs:
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:

  - script: |
      cd ios
      bundle install --retry=3 --jobs=4
    displayName: 'bundle install'

  - script: |
      cd ios
      bundle exec fastlane -v
    displayName: 'bundle exec fastlane -v'

  - script: |
      cd ios
      bundle exec fastlane environment
    displayName: 'bundle exec fastlane environment'

  - script: |
      cd ios
      bundle exec fastlane all
    displayName: 'bundle exec fastlane all'
    env:
      FASTLANE_PASSWORD: $(FASTLANE_PASSWORD)
