steps:

# config

- task: UseRubyVersion@0
  inputs:
    versionSpec: '>= 2.5'
  condition: not(eq(variables['Agent.OS'], 'Darwin'))

# preparation

- script: gem install bundler
  displayName: 'install bundler'
  condition: not(eq(variables['Agent.OS'], 'Darwin'))

- script: |
    cd android
    bundle install --retry=3 --jobs=4
  displayName: 'bundle install'

- script: |
    cd android
    bundle exec fastlane -v
  displayName: 'bundle exec fastlane -v'

## Android Tools

- script: |
    xcopy "%ANDROID_HOME%/tools" "%ANDROID_HOME%/tools.old" /e /i /h
    echo "y" | "%ANDROID_HOME%/tools.old/bin/sdkmanager" "system-images;android-27;google_apis;x86"
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  displayName: 'install android tools (Windows)'

- bash: |
    echo "y" | $ANDROID_HOME/tools/bin/sdkmanager --install 'system-images;android-27;google_apis;x86'
  condition: eq(variables['Agent.OS'], 'Darwin')
  displayName: 'install android tools (Mac)'

# secure files

- task: DownloadSecureFile@1
  inputs:
    secureFile: google_play_key.json

- task: DownloadSecureFile@1
  inputs:
    secureFile: zaehlerstand.keystore

- script: |
    echo %DOWNLOADSECUREFILE1_SECUREFILEPATH%
    echo %DOWNLOADSECUREFILE2_SECUREFILEPATH%
    REM https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#set-in-script
    echo ##vso[task.setvariable variable=JSON_KEY_FILE]%DOWNLOADSECUREFILE1_SECUREFILEPATH%
    echo ##vso[task.setvariable variable=KEYSTORE_FILE]%DOWNLOADSECUREFILE2_SECUREFILEPATH%
  condition: eq(variables['Agent.OS'], 'Windows_NT')
  displayName: 'copy secure file filenames to environment variables (Windows)'

- script: |
    echo $DOWNLOADSECUREFILE1_SECUREFILEPATH
    echo $DOWNLOADSECUREFILE2_SECUREFILEPATH
    # https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=vsts&tabs=yaml%2Cbatch#set-in-script
    echo "##vso[task.setvariable variable=JSON_KEY_FILE]$DOWNLOADSECUREFILE1_SECUREFILEPATH"
    echo "##vso[task.setvariable variable=KEYSTORE_FILE]$DOWNLOADSECUREFILE2_SECUREFILEPATH"
  condition: or(eq(variables['Agent.OS'], 'Linux'), eq(variables['Agent.OS'], 'Darwin'))
  displayName: 'copy secure file filenames to environment variables (Linux / Mac)'

# make gradlew executable

- bash: |
    cd android/androidapp
    chmod +x gradlew
  condition: or(eq(variables['Agent.OS'], 'Linux'), eq(variables['Agent.OS'], 'Darwin'))
  displayName: 'make gradlew executable (Linux / Mac)'

# lanes

- script: |
    cd android
    bundle exec fastlane environment
  displayName: 'bundle exec fastlane environment'

- script: |
    cd android
    bundle exec fastlane all
  displayName: 'bundle exec fastlane all'
